### ISSUE TITLE
`chbder_vector` not creating the correct results

### ISSUE THREAD

**Issue by esimpsons3ti** [SETI/rms-cspyce#150]
The function `cspyce.chbder` returns the value of a polynomial and its first `nderiv` derivatives, evaluated at the input `x`, using the coefficients of the Chebyshev expansion of the polynomial. Here are the inputs and returns for the vectorized version:

```
    Inputs:
      float[_,*] cp     = degp+1 Chebyshev polynomial coefficients.
      float[_,2] x2s    = Transformation parameters of polynomial.
      float[_]   x      = Value for which the polynomial is to be evaluated.
      int        nderiv = The number of derivatives to compute.
    
    Returns:
      float[_]   dpdxs  = Array of the derivatives of the polynomial.
```

It should be noted that, if the arguments used in the vectorized version are the same as the scalar version, it should give the same answer. Here is the scalar version of the test:
```
import cspyce as cs
import numpy.testing as npt

cp = [1.0, 3.0, 0.5, 1.0, 0.5, -1.0, 1.0]
x2s = [0.5, 3.0]
dpdxs = cs.chbder(cp, x2s, 1.0, 3)
npt.assert_array_almost_equal([-0.340878, 0.382716, 4.288066, -1.514403],
                              dpdxs)
```

This passes no problem. But when this same test is vectorized (and nothing else changes), it gives an error:

```
AssertionError: 
Arrays are not almost equal to 6 decimals

Mismatched elements: 4 / 4 (100%)
Max absolute difference: 4.288066
Max relative difference: 1.340878
 x: array([-0.340878,  0.382716,  4.288066, -1.514403])
 y: array([1., 0., 0., 0.])
```

It is likely that there is a bug for `chbder_vector` that needs to be addressed.

**Comment by fyellin** [comment]
Great catch!

There's a bug in chbder_vector.   At line #494 of cspyce0_part2.i, it should be
`int degp = in21_dim2 - 1` instead of `int depg = in21_dim1 - 1`.  

If you pass this function say, a 3x10 vector as a first argument, the 3x is the vectorization, where the actual polynomial is x10 and so has a degree of 9.

**Comment by fyellin** [comment]
Emilie, do you want to fix this, or should I?

**Comment by esimpsons3ti** [comment]
@fyellin I can fix this. Thank you for sharing the solution!
