### ISSUE TITLE
Tests fail on Windows in gfocce

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-cspyce#151]
The automated GitHub tests fail on Windows hosts for all versions of Python. The problem appears to be in the executed of the test for `gfocce`.

```
unittests/test_f_j.py::test_gfevnt PASSED                                [ 45%]
unittests/test_f_j.py::test_gffove PASSED                                [ 45%]
unittests/test_f_j.py::test_gfilum PASSED                                [ 45%]
unittests/test_f_j.py::test_gfocce 
Error: Process completed with exit code 1.
```

**Comment by fyellin** [comment]
The two tests that are failing on windows are test_gfocce and test_gfoclt.  I will look to see if I can figure out what's going on with these using only github.

**Comment by fyellin** [comment]
When running both these tests (separately) with a flag saying to actually show what's in standard output, I get
```
SPICE(BADSUBSCRIPT): Subscript out of range on file line 1626, procedure "zzgfocu". Attempt to access element 1 of variable "svbrad".

A traceback follows. The name of the highest level module is first.
gfocce_c->GFOCCE->ZZGFSOLV->ZZGFOCST
```

Essentially the same message from gfoclt.

Do we know if there has been any source change in this last several months?  I'm looking at zzgfocu.c and not seeing anything on line 1626 that looks remotely reasonable.

**Comment by rfrenchseti** [comment]
The NAIF source code never changes unless they release an entire new version.

**Comment by fyellin** [comment]
There was *no* change to our source code between 10/29 (the tests passed)
and 11/5 (the tests failed).  I'm investigation if it's possible to install
an older version of the C compiler (or to find an older github runner) to
see if that's really the issue.

**Comment by fyellin** [comment]
Just to gather some notes:

Run #310.  October 29.  Windows-latest 3.11.  Last successful run
     [Log](https://github.com/SETI/rms-cspyce/actions/runs/6683031720/job/18158827226)
     Version: 20231024.1.0
     [Included Software](https://github.com/actions/runner-images/blob/win22/20231024.1/images/win/Windows2022-Readme.md)
     C compiler: `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe`

Run #311.  November 4.  Windows-latest 3.11.  Fail
     [Log](https://github.com/SETI/rms-cspyce/actions/runs/6760975286/job/18379595296)
     Version: 20231029.1.0
     [Included Software](https://github.com/actions/runner-images/blob/win22/20231029.1/images/win/Windows2022-Readme.md)
     C compiler: `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe`

The version and included software are from expanding "Set up Job" > "Runner Image" in the log.  The C compiler was determined by running:
```
python3 -c 'import distutils.ccompiler as cc; x = cc.new_compiler(); x.initialize(); print(x.cc)'
```

This [document](https://github.com/actions/runner-images/releases/tag/win22%2F20231029.1) shows the difference between the windows images of 10/24 and 10/29.  There does not appear to be any changes that would affect us.  

I do not understand why the name of the C compiler (as reported by Python) is so different between the two Windows images.  Those version numbers do not appear anywhere in the lists of included software.

Looking at the Python requirements between the two logs, the only difference is that one loads in charset_normalizer 3.3.1 and the other loads in 3.3.2.  The problem still occurs even if I force 3.3.1 into the image.

I'm really not sure how to continue at this point
