### ISSUE TITLE
cspyce doesn't compile on MacOS due to lack of swig

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-cspyce#163]
It appears GitHub has removed swig from the MacOS runners. We need to somehow install swig during the test action.

**Comment by fyellin** [comment]
Just so it's written down.

Failing image:
Runner Image
  Image: macos-14-arm64
  Version: 20240422.3
  Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20240422.3/images/macos/macos-14-arm64-Readme.md

Working Image:
Runner Image
  Image: macos-12
  Version: 20240412.2
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20240412.2/images/macos/macos-12-Readme.md

Looking at the "included software", it is clear than Swig has been dropped for unknown reasons.  Will investigate the right way to install it ourselves.

[Above info is from clicking on the logs, Clicking on the first item "Set up job", and then opening up the item "Runner Image".]
