### ISSUE TITLE
Create cspyce unit tests

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-cspyce#17]
Create unit tests for cspyce. These could take two forms, and be added to over time:
- Tests for the basic cspyce data types, to make sure that the C/Python interface is working properly.
- Tests for the actual CSPICE functions to make sure that the proper results are returned.

The eventual goal would be 100% code coverage and as such adding a code coverage process is important.

**Comment by matthewtiscareno** [comment]
This should eventually be a project, and its many individual aspects should be entered as bite-sized issues.  That said, I acknowledge that we don't yet know how the issues will be organized.

**Comment by rfrenchseti** [comment]
I'm downgrading the priority because hopefully this will end up being addressed by Joe's PDART proposal.

**Comment by rfrenchseti** [comment]
This has been mostly completed and the remaining areas of cspyce that need new tests have their own issues now.
