### ISSUE TITLE
cspyce automated build failing on MacOS Python 3.12

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-cspyce#172]
The automated tests are failing on MacOS with Python 3.12. I don't see an obvious reason in the Action logs. For some reason the SPICE library is not available for linking.

**Comment by fyellin** [comment]
There seems to have been some screw up with the cache.  I don't know what.  I deleted the github cache for Macos-3-12 and everything seems to work fine now.

I'll wait a day or two before either closing this myself or having Rob close it, just to make sure everything really is okay.
